name: CI

on:
  schedule:
  - cron: "* * * * *"

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Pakages: ['@capgo/capacitor-updater', 'vue-timer-hook']
  
    steps:
      - name: Check if package is available
        run: npm i ${{matrix.Pakages}}
