name: Main

on:
  schedule:
  - cron: "*/5 * * * *"
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Pakages: [
          '@capgo/capacitor-updater',
          'vue-timer-hook',
          'capacitor-standard-version',
          '@capgo/capacitor-purchases',
          '@capgo/nativegeocoder',
          '@capgo/capacitor-screen-recorder',
          '@capgo/capacitor-flash',
          '@capgo/capacitor-mute',
          '@capgo/native-market',
          '@capgo/capacitor-crisp',
          '@capgo/inappbrowser'
        ]
        Commands: ['yarn add', 'npm i', 'pnpm i']
  
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Check if package is available in "${{matrix.Commands}}"
        run: ${{matrix.Commands}} ${{matrix.Pakages}}
