name: Main

on:
  schedule:
  - cron: "*/5 * * * *"
  workflow_dispatch:
  
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Nodes: [14.x, 15.x, 16.x, 17.x, 18.x]
        PnpmVersion: [6, 7]
        Pakages: [
          '@capgo/capacitor-updater',
          'vue-timer-hook',
          'capacitor-standard-version',
          '@capgo/capacitor-purchases',
          '@capgo/nativegeocoder',
          '@capgo/capacitor-screen-recorder',
          '@capgo/capacitor-flash',
          '@capgo/capacitor-mute',
          '@capgo/native-market',
          '@capgo/capacitor-crisp',
          '@capgo/inappbrowser'
        ]
  
    steps:
      - name: Use Node.js ${{ matrix.Nodes }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.Nodes }}
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.PnpmVersion }}
      - name: Check if package is available in yarn
        run: yarn add ${{matrix.Pakages}}
      - name: Check if package is available in npm
        run: npm i ${{matrix.Pakages}}
      - name: Check if package is available in pnpm
        run: pnpm i ${{matrix.Pakages}}
