name: Main

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Pakages: ['@capgo/capacitor-updater', 'vue-timer-hook']
  
    steps:
      - name: Check if package is available in npm
        run: npm i ${{matrix.Pakages}}
      - name: Check if package is available in yarn
        run: yarn add ${{matrix.Pakages}}
      - name: Check if package is available in pnpm
        run: pnpm i ${{matrix.Pakages}}
